name: Chat Service CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'services/chat-service/**'
      - '.github/workflows/chat-service.yml'
      - '.github/workflows/ci-cd_pipeline_template.yml'
  workflow_dispatch:

jobs:
  chat-service:
    uses: ./.github/workflows/ci-cd_pipeline_template.yml
    with:
      language: 'node'
      service_name: 'chat-service'
      workdir: 'services/chat-service'
      app_name: 'easybake-chat-service'
      artifact_name: 'chat-app'
    secrets:
      PUBLISH_PROFILE: ${{ secrets.AZURE_CHAT_SERVICE_SWEDEN_PUBLISH_PROFILE }}
