name: Build iOS IPA
on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-14
    defaults:
      run:
        working-directory: apps/easy_bake_mobile

    steps:
      - uses: actions/checkout@v4
      
      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Clean Cache and Install Dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Patch device_info_plus
        run: |
          TARGET_FILE=$(find /Users/runner/.pub-cache -name "FPPDeviceInfoPlusPlugin.m" | head -n 1)
          # Replace the broken Vision Pro calls with the boolean NO
          sed -i '' 's/\[\[NSProcessInfo processInfo\] isiOSAppOnVision\]/NO/g' "$TARGET_FILE"
          sed -i '' 's/\[info isiOSAppOnVision\]/NO/g' "$TARGET_FILE"

      - name: Build Frameworks
        run: flutter build ios --release --no-codesign
        
      - name: Create IPA
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r ../../../EasyBake.ipa Payload
          
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: EasyBake.ipa